/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    copy: typeof import('./src/components/ShippingPopup copy.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    InputSwitch: typeof import('primevue/inputswitch')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MyCustomComponent: typeof import('./src/components/MyCustomComponent.vue')['default']
    Option: typeof import('./src/components/product/Option.vue')['default']
    OptionsGroup: typeof import('./src/components/product/OptionsGroup.vue')['default']
    ProductSummary: typeof import('./src/components/product/ProductSummary.vue')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RequirementsPopup: typeof import('./src/components/RequirementsPopup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectedConfiguration: typeof import('./src/components/product/SelectedConfiguration.vue')['default']
    ShippingPopup: typeof import('./src/components/ShippingPopup.vue')['default']
    TheFooter: typeof import('./src/components/generic/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/generic/TheHeader.vue')['default']
  }
}
